date has many hidden info like day(numeric) month year is it weekday which decade which day like monday etc

In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working with data

In [9]:
date['date'] = pd.to_datetime(date['date']) # so that apde date time functions apply kari sakiye so changing the data type of date col of date data

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
date['date_year'] = date['date'].dt.year

In [12]:
date.sample(5)

          date  product_id  city_id  orders  date_year
116 2019-04-23        4523       13       1       2019
198 2018-08-28         685       25      29       2018
499 2018-09-28        1225       13      40       2018
680 2019-11-17        4111       18       2       2019
668 2019-11-01        6937       13      38       2019

In [13]:
date['date-month'] = date['date'].dt.month

In [14]:
date['date-month-name'] = date['date'].dt.month_name()

In [15]:
date['date-day'] = date['date'].dt.day

In [16]:
date['date-dow'] = date['date'].dt.dayofweek

In [18]:
date['date-dayname'] = date['date'].dt.day_name()

In [19]:
date['is_weekend'] = np.where(date['date-dayname'].isin(['Sunday','Saturday']),1,0)

In [20]:
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date-month,date-month-name,date-day,date-dow,dtae-dayname,date-dayname,is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,Sunday,1

In [23]:
date['date_week'] = date['date'].dt.isocalendar().week

In [24]:
date['quarter'] =  date['date'].dt.quarter

In [25]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)

In [30]:
import datetime

In [31]:
today = datetime.datetime.today()

In [32]:
today - date['date']

0     2436 days 18:23:49.125704
1     2918 days 18:23:49.125704
2     2849 days 18:23:49.125704
3     2551 days 18:23:49.125704
4     2774 days 18:23:49.125704
                 ...
995   2864 days 18:23:49.125704
996   2805 days 18:23:49.125704
997   2653 days 18:23:49.125704
998   2718 days 18:23:49.125704
999   2492 days 18:23:49.125704
Name: date, Length: 1000, dtype: timedelta64[ns]

In [33]:
(today-date['date']).dt.days

0      2436
1      2918
2      2849
3      2551
4      2774
       ...
995    2864
996    2805
997    2653
998    2718
999    2492
Name: date, Length: 1000, dtype: int64

In [37]:
# Months passed
# (Year difference * 12) + Month difference

np.round((today.year - date['date'].dt.year) * 12 + (today.month - date['date'].dt.month), 0)

0      80
1      96
2      94
3      84
4      91
       ..
995    94
996    92
997    87
998    89
999    82
Name: date, Length: 1000, dtype: int32

In [38]:
time['date'] = pd.to_datetime(time['date'])

In [39]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [40]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [41]:
today - time['date']

0     4622 days 17:33:49.125704
1     4486 days 18:43:49.125704
2     4972 days 18:02:49.125704
3     4274 days 17:52:49.125704
4     4671 days 19:12:49.125704
                 ...
995   5261 days 17:33:49.125704
996   4582 days 19:09:49.125704
997   5047 days 18:46:49.125704
998   5163 days 18:49:49.125704
999   4435 days 18:58:49.125704
Name: date, Length: 1000, dtype: timedelta64[ns]

In [42]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.994040e+08
1      3.876578e+08
2      4.296458e+08
3      3.693380e+08
4      4.036436e+08
           ...
995    4.546136e+08
996    3.959538e+08
997    4.361284e+08
998    4.461510e+08
999    3.832523e+08
Name: date, Length: 1000, dtype: float64

In [43]:
# in months

(today - time['date'])/np.timedelta64(1,'m')

0      6.656734e+06
1      6.460964e+06
2      7.160763e+06
3      6.155633e+06
4      6.727393e+06
           ...
995    7.576894e+06
996    6.599230e+06
997    7.268807e+06
998    7.435850e+06
999    6.387539e+06
Name: date, Length: 1000, dtype: float64

In [44]:
# in hrs

(today - time['date'])/np.timedelta64(1,'h')

0      110945.563646
1      107682.730313
2      119346.046979
3      102593.880313
4      112123.213646
           ...
995    126281.563646
996    109987.163646
997    121146.780313
998    123930.830313
999    106458.980313
Name: date, Length: 1000, dtype: float64