## all the commands we can find in pandas documentation under pandas.read_csv API reference

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('aug_test.csv')

In [4]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

## first we opened csv that is local file i.e on our machine

## now we are opening a csv file from an url

In [5]:
import requests
from io import StringIO
# rest we'll google when we need

## SEP PARAMETER
# in csv it is automatically seperated with comma so we dont have to pass this parameter but in tsv to make it readable we pass sep parameter....'\t'

In [6]:
pd.read_csv('movie_titles_metadata.tsv',sep='\t')
# aama ato aave che col names but agar na aave the by default 1st row becomes col names
# thus we after sep pass another parameter names=['','',....] col names

     movie_id       title  release_year      genre  rating    votes
0           1     Movie_1          2020     Action     5.1  1154556
1           2     Movie_2          1995      Crime     5.7   430895
2           3     Movie_3          2023    Romance     5.4  1770668
3           4     Movie_4          1982      Drama     5.4   976850
4           5     Movie_5          2012  Adventure     5.1   834985
..        ...         ...           ...        ...     ...      ...
995       996   Movie_996          2012  Animation     8.0   520560
996       997   Movie_997          2023      Drama     6.2  2051120
997       998   Movie_998          2018    Mystery     5.9  1991542
998       999   Movie_999          2017    Romance     6.7   686825
999      1000  Movie_1000          1996     Action     6.4  1622373

[1000 rows x 6 columns]

## Header parameter
so if the col names becomes part of data like 1st row is col names

In [7]:
pd.read_csv('test.csv')
# here its not this case... when it is we add a parameter header=1

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,0,1,8,1,0,0,1,0,0,...,1,1,1,12,0,1,1,0,0,1
1,1,4,2,5,1,0,0,0,0,1,...,2,0,3,10,0,0,1,1,0,1
2,2,5,1,3,0,0,0,0,0,1,...,4,0,2,4,0,0,0,0,0,0
3,3,0,1,6,0,0,1,0,0,0,...,5,1,0,5,1,0,1,0,0,0
4,4,5,1,7,0,0,0,0,0,1,...,4,0,0,4,0,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892811,1488022,0,1,6,0,0,0,1,0,0,...,4,2,3,4,0,1,0,0,1,0
892812,1488023,5,3,5,1,0,0,0,1,0,...,6,2,2,11,0,0,1,1,0,0
892813,1488024,0,1,5,0,0,1,0,0,0,...,5,2,2,11,0,1,1,0,0,0
892814,1488025,6,1,5,1,0,0,0,0,1,...,1,1,2,7,1,1,0,0,0,0
892815,1488026,7,1,4,1,0,0,0,0,1,...,5,2,2,7,0,1,1,1,0,0

## Index_col parameter

In [8]:
pd.read_csv('aug_test.csv',index_col='enrollee_id')
#  the col we dont want in analysis and have unique values for diff enteries can be made as index col

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
enrollee_id,,,,,,,,,,,,
32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21
9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...
1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

## use cols_parameter
when uk what cols u dont want so while importing data you can import only specific cols

In [9]:
pd.read_csv('aug_test.csv',usecols=['city','gender'])

          city  gender
0      city_41    Male
1     city_103  Female
2      city_21    Male
3      city_13    Male
4     city_103    Male
...        ...     ...
2124  city_103    Male
2125  city_136    Male
2126  city_100    Male
2127  city_102    Male
2128  city_102    Male

[2129 rows x 2 columns]

## Squeeze Parameter
when we need 1 col(rarely) we use squeeze() so that we get pandas series not dataframe

In [10]:
pd.read_csv('aug_test.csv', usecols=['city']).squeeze()

0        city_41
1       city_103
2        city_21
3        city_13
4       city_103
          ...
2124    city_103
2125    city_136
2126    city_100
2127    city_102
2128    city_102
Name: city, Length: 2129, dtype: str

## Skip rows/n rows Parameter

In [11]:
pd.read_csv('aug_test.csv',skiprows=[1,3,5,7]) 
# 1 is the 1st row index 0

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
1,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
2,217,city_23,0.899,Male,No relevent experience,Part time course,Masters,STEM,10,NaN,NaN,2,12
3,27302,city_160,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,>4,81
4,12994,city_173,0.878,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2120,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2121,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2122,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2123,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2124,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

In [12]:
pd.read_csv('aug_test.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

In [13]:
pd.read_csv('aug_test.csv', skiprows=lambda x: x % 2 != 0)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
1,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
2,217,city_23,0.899,Male,No relevent experience,Part time course,Masters,STEM,10,NaN,NaN,2,12
3,27302,city_160,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,>4,81
4,16287,city_21,0.624,Male,Has relevent experience,Full time course,Graduate,NaN,3,50-99,Funded Startup,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059,8905,city_70,0.698,NaN,No relevent experience,Full time course,High School,NaN,8,NaN,NaN,never,55
1060,27163,city_173,0.878,Male,No relevent experience,no_enrollment,Masters,STEM,16,<10,Pvt Ltd,>4,58
1061,21339,city_21,0.624,Female,No relevent experience,Full time course,High School,NaN,3,NaN,NaN,never,56
1062,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
1063,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84

In [14]:
pd.read_csv('aug_test.csv',nrows=100)
# nrows give the no. of rows we type here 100 so we get 100 rows

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2934,city_75,0.939,Male,Has relevent experience,no_enrollment,Phd,STEM,>20,1000-4999,Pvt Ltd,3,328
96,12919,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,Humanities,4,NaN,NaN,1,47
97,4386,city_21,0.624,Male,No relevent experience,Full time course,High School,NaN,3,<10,Early Stage Startup,2,36
98,22462,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,9,10000+,NGO,1,30
99,13988,city_103,0.920,NaN,Has relevent experience,Part time course,Masters,STEM,16,10000+,Pvt Ltd,>4,36

## Encoding parameter
utf-8 hoy generally but in some cases it is not so when we do read_csv it throws a unicodeDecodeError
so tyare we have to enter parameter of encoding j aenu type hoy

for eg-> if encoding is latin-1
then

pd.reas_csv('',encoding='latin-1')

how to know encoding google it

## Skip bad lines
means koi row ma col karta vadhare values che

In [15]:
pd.read_csv('BX-Books.csv',encoding='latin-1',sep=';',on_bad_lines='skip')

C:\Users\MAANSHA\AppData\Local\Temp\ipykernel_7452\3337764909.py:1: DtypeWarning: Columns (0: 2002) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('BX-Books.csv',encoding='latin-1',sep=';',on_bad_lines='skip')

,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
1,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
2,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
3,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
4,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...
...,...,...,...,...,...,...,...,...
271354,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271355,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271356,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271357,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271358,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

## dtype parameters
we change the data type of cols to save memory sometimes

In [16]:
pd.read_csv('aug_test.csv').info()

<class 'pandas.DataFrame'>
RangeIndex: 2129 entries, 0 to 2128
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             2129 non-null   int64
 1   city                    2129 non-null   str
 2   city_development_index  2129 non-null   float64
 3   gender                  1621 non-null   str
 4   relevent_experience     2129 non-null   str
 5   enrolled_university     2098 non-null   str
 6   education_level         2077 non-null   str
 7   major_discipline        1817 non-null   str
 8   experience              2124 non-null   str
 9   company_size            1507 non-null   str
 10  company_type            1495 non-null   str
 11  last_new_job            2089 non-null   str
 12  training_hours          2129 non-null   int64
dtypes: float64(1), int64(2), str(10)
memory usage: 216.4 KB

In [17]:
pd.read_csv('aug_test.csv',dtype={'city_development_index':float}).info()
# float takes more memory than int but no other opt as col j float ma che int ma thati nathi

<class 'pandas.DataFrame'>
RangeIndex: 2129 entries, 0 to 2128
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             2129 non-null   int64
 1   city                    2129 non-null   str
 2   city_development_index  2129 non-null   float64
 3   gender                  1621 non-null   str
 4   relevent_experience     2129 non-null   str
 5   enrolled_university     2098 non-null   str
 6   education_level         2077 non-null   str
 7   major_discipline        1817 non-null   str
 8   experience              2124 non-null   str
 9   company_size            1507 non-null   str
 10  company_type            1495 non-null   str
 11  last_new_job            2089 non-null   str
 12  training_hours          2129 non-null   int64
dtypes: float64(1), int64(2), str(10)
memory usage: 216.4 KB

## Handling dates
dates str ma hoy to aene int jeva ma karye to date operations lagaday i.e aa date thi aani vache and all that stuff

In [46]:
# pd.read_csv('',parse_dates=['date',...])

In [48]:
# if yr day month cols alag and we want to club all 3 to 1 col(feature eng) then we can-->
# ,parse_dates=[[1,2,3]] --> 1 2 3 will be parsed into single date col

## Converters

In [50]:
# def rename(name):
#     if name=='':
#         return ""
#     else:
#         return name


# pd.read_csv('',converters={'col':renam})

## na_values
jya data ma - che instead of nan...

In [53]:
# pd.read_csv('',na_values=['-',..])

## Loading huge dataset

so dataset bav moto che so aakha pr operation aek sathe na thya due to memory limitations so we divide dataset in chuncks

In [55]:
# dfs = pd.read_csv('',chunksize=5000)

# for chunk in dfs:
#     print(chunk.shape)  --> barabar ma divide thase groupby badhuu chale but we have to do in  loop