MICE = multivariate imputation by chained equations

there are 3 types of missing data assumptions
1. MCAR ==> missing completely at random
            bija rows thi aeni val fill na thay and data is still raw...
2. MAR ==> missing at random
           bija rows thi aeni values fill thay i.e data has some corelation
3. MNAR ==> missing not at random
            data thi hathe karine values remove thyi che

We can use MICE in all 3 cases but best result in MAR

ADVANTAGE 
1. Accurate

DISADVANTAGE
1. slow
2. server pr training dataset mukvu pade for prediction

When u have multiple numerical values to handle like price temp etc rather than discrete categorical then its a regression problem

Regression: Predicts a number ("How much?").

Classification: Predicts a category ("Which class?").

Linear RegressionPurpose: Predicts a continuous quantity.
Output: Any real number (from negative infinity to positive infinity).

Logistic RegressionPurpose: Predicts the probability of a categorical outcome.
Output: A value between 0 and 1 (which maps to a class like "Yes" or "No").

In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [3]:
df.head()

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [4]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0